### ISSUE TITLE
Can not select text on iOS. 

### ISSUE THREAD

**Issue by momja** [KillerCodeMonkey/ngx-quill-ionic#1]
Do you have any suggestions on how to make text selectable in iOS? Typing and formatting works great, but I cannot select a portion of text. I followed along [this](https://github.com/KillerCodeMonkey/ngx-quill/issues/86) issue but doesn’t seem to fix the problem.

**Comment by KillerCodeMonkey** [comment]
I only know this css trick to reactivate user-select:
https://github.com/KillerCodeMonkey/ngx-quill-ionic-v4#how-to-use

Maybe there is another css selector that is overwriting this on iOS?

**Comment by momja** [comment]
I'll keep looking. If I find anything I'll post it here. Have you had any luck getting it to work on iOS?

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by momja** [comment]
No luck. This is still a persistent problem.

**Comment by KillerCodeMonkey** [comment]
did you tried it without ionic? Maybe they changed some css selectors for contenteditable elements.

In general it worked for me setting the user-select css attribute.

But i never tried it with ionic 4.x on ios

**Comment by momja** [comment]
I've had it work without ionic before. Unfortunately, I'm not working on it anymore. It might be a good idea for someone to test in iOS. Maybe it was a problem with my setup.

**Comment by KillerCodeMonkey** [comment]
hey @momja long time no see. I updated the repo to ionic v5. do you have any updates on it?

**Comment by KillerCodeMonkey** [comment]
https://github.com/quilljs/quill/issues/2778
https://github.com/quilljs/quill/issues/2787
