### ISSUE TITLE
Error : import QuillType, { Delta } from 'quill';

### ISSUE THREAD

**Issue by elmor34** [KillerCodeMonkey/ngx-quill-ionic#35]
In the sample as it is with Angular 9.1.4 and @ionic/angular": "^5.1.0, ngx-quill":10.0.1    I get following error message : 

Also in Angular 13.2.2 and  ionic 6.0.0 and  ngx-quill: 5.0.0 or 16.2.0. get same messages : 

[ngx-quill-example].  for  Angular 13.2.2. works perfect without problem.
( even after applying advices as :

_[ng]     ERROR in node_modules/@types/quill/node_modules/quill-delta/dist/Delta.d.ts:1:8 - error TS1259: Module '"/Users/gokhan/test/ngx-quill-ionic-master/node_modules/@types/quill/node_modules/fast-diff/diff"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
[ng]     
[ng]     **1 import diff from 'fast-diff';**
[ng]              ~~~~
[ng]     
[ng]       node_modules/@types/quill/node_modules/fast-diff/diff.d.ts:20:1
[ng]         **20 export = diff;**
[ng]            ~~~~~~~~~~~~~~
[ng]         This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
[ng]     node_modules/ngx-quill/lib/quill-editor.component.d.ts:3:21 - error TS2614: Module '"../../@types/quill"' has no exported member 'Delta'. **Did you mean to use 'import Delta from "../../@types/quill"' instead?
[ng]     
[ng]     3 import QuillType, { Delta } from 'quill';**
[ng]                           ~~~~~
[ng]_

**Comment by KillerCodeMonkey** [comment]
I mean the solution is stated in the error message.

Just allow *allowSyntheticDefaultImports in tsconfig.*

*Or just checkout the working demo repo linked in the readme.*

Gokhan ***@***.***> schrieb am So., 8. Mai 2022, 13:50:
